items:
  - colors:
      name: 3024 (dark)
      author: Chris Kempson
      primary:
        background: "#090300"
        foreground: "#a5a2a2"
      cursor:
        text: "#090300"
        cursor: "#a5a2a2"
      normal:
        black: "#090300"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#a5a2a2"
      bright:
        black: "#5c5855"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#f7f7f7"
  - theme: 3024.dark
colors:
  # Default colors
  primary:
    background: '#282c34'
    foreground: '#abb2bf'

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black: '#282c34'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#d19a66'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#abb2bf'

  # Bright colors
  bright:
    black: '#5c6370'
    red: '#e06c75'
    green: '#98c379'
    yellow: '#d19a66'
    blue: '#61afef'
    magenta: '#c678dd'
    cyan: '#56b6c2'
    white: '#ffffff'
theme: One-Dark

# 设置字体
font:
  normal:
    family: "Hack Nerd Font"
    style: Regular
  bold:
    family: "Hack Nerd Font"
    style: Bold
  italic:
    family: "Hack Nerd Font"
    style: Italic
  bold_italic:
    family: "Hack Nerd Font"
    style: Bold Italic

  # 字大小
  size: 9.0

  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

window:
  padding:
    x: 2
    y: 2
